In [1]:
Output = c("/Users/alexis/Library/CloudStorage/OneDrive-UniversityofNorthCarolinaatChapelHill/CEMALB_DataAnalysisPM/Projects/P1014. Nanoparticles Respiratory Tract/P1014.3. Analyses/P1014.3.1. Group Distribution Analysis/Output")
cur_date = "021326"

library(readxl)
library(openxlsx)
library(tidyverse)
library(reshape2)
library(rlang)
library(limma)

# reading in files
protein_df = data.frame(read_excel("Input/Protein_Data_020926.xlsx", sheet = 2))[,4:13]
protein_df$Dose = as.numeric(protein_df$Dose)

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.5
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.4     ✔ tidyr     1.3.1
✔ purrr     1.1.0
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘reshape2’


The following object is masked from ‘package:tidyr’:

    smiths



Attaching package: ‘rlang’


The following objects are masked from ‘package:purrr’:

    %@%, flatten, flatten_chr, flatten_dbl, flatten_int, flatten_lgl,
    flatten_raw, invoke, splice

In [2]:
head(protein_df)

  Subject_No Treatment       Sample_ID              Dose Separation ELISA_ID
1 1          NP1-Rhodamine B NP1-Rhodamine B_1_0.05 0.05 R          nEL03001
2 1          NP1-Rhodamine B NP1-Rhodamine B_1_0.05 0.05 R          nEL03541
3 1          NP1-Rhodamine B NP1-Rhodamine B_1_0.05 0.05 R          nEL01701
4 1          NP1-Rhodamine B NP1-Rhodamine B_1_0.05 0.05 R          nEL04271
5 1          NP1-Rhodamine B NP1-Rhodamine B_1_0.05 0.05 R          nEL03101
6 1          NP1-Rhodamine B NP1-Rhodamine B_1_0.05 0.05 R          nEL09731
  UniProt_ID Protein_Name        Conc     Conc_pslog2
1 Q07011     4-1BB               2.002402 1.586117
2 Q15109     AGER                3.425807 2.145941
3 Q9UNG2     AITRL (GITR Ligand) 2.178579 1.668382
4 P31749     AKT1                2.214532 1.684609
5 Q15389     Angiopoietin-1      2.611234 1.852492
6 P05089     ARG1                3.369304 2.127404

In [3]:
# only interested in centrifuged samples
protein_df = protein_df %>%
    filter(Separation == 'C')

we are interested in comparing NP1_Rhodamine B and NP2 with Vehicle control. For NP1 and NP1_Rhodamine B, two doses are available. 
Let's answer this with a 

Now on the data analysis side, we are interested in dose-dependent effect of NP1 and NP1_Rhodamine B. A comparison between NP1 and NP1_Rhodamine B will also be informative. Ultimately, the effect of NP2 and NP2_Rhodamine B (with only n=1) at the higher dose will be very informative. Comparison between NP1 and NP2 at the higher dose will be informative too.


## Is there a statistically significant difference in protein expression in respiratory tract cells based on treatment? How does this expression change with dose?

We'll use linear modeling to compare, NP1 (at both doses), NP1-Rhodamine B (at both doses) and NP2 to controls.

In [4]:
# converting to a wide format to run limma
wide_protein_matrix = protein_df %>%
    select(Sample_ID, UniProt_ID, Conc_pslog2) %>%
    pivot_wider(names_from = Sample_ID, values_from = Conc_pslog2) %>%
    column_to_rownames("UniProt_ID") %>%
    as.matrix()

head(wide_protein_matrix)

       Control_2_NA NP1_3_0.1 NP1-Rhodamine B_5_0.1 NP1_6_0.05
Q07011 1.585350     1.569602  1.569492              1.572613
Q15109 2.135693     2.138565  2.141932              2.143017
Q9UNG2 1.642756     1.654883  1.636094              1.646805
P31749 1.670583     1.680710  1.675403              1.663189
Q15389 1.896098     1.773931  1.819644              1.803776
P05089 2.120742     2.121573  2.120719              2.109544
       NP1-Rhodamine B_8_0.05 Control_10_NA NP1_11_0.1 NP1-Rhodamine B_13_0.1
Q07011 1.576097               1.583870      1.605838   1.582235
Q15109 2.133122               2.073869      2.129192   2.129461
Q9UNG2 1.645349               1.674437      1.661696   1.657174
P31749 1.665997               1.663760      1.660594   1.666499
Q15389 1.843614               1.877910      1.776046   1.818144
P05089 2.123041               2.113760      2.128535   2.126708
       NP1_14_0.05 NP2_Rhodamine B_15_0.1 NP1-Rhodamine B_16_0.05 Control_17_NA
Q07011 1.554672    1.554169               1.582363                1.575114
Q15109 2.148347    2.137005               2.125730                2.138415
Q9UNG2 1.650657    1.654289               1.649807                1.629017
P31749 1.667402    1.663113               1.683948                1.649666
Q15389 1.791555    1.709945               1.860328                1.851314
P05089 2.149856    2.117535               2.133877                2.121512
       NP2_18_0.1 NP1_20_0.1 NP1-Rhodamine B_21_0.1 NP2_22_0.1 NP1_24_0.05
Q07011 1.584561   1.592782   1.568494               1.573283   1.576927
Q15109 2.145104   2.115151   2.133203               2.128770   2.139980
Q9UNG2 1.652983   1.664520   1.664310               1.658886   1.660484
P31749 1.686324   1.671090   1.677939               1.693824   1.684437
Q15389 1.684969   1.783841   1.817430               1.677256   1.810487
P05089 2.109153   2.133167   2.131711               2.129999   2.132945
       NP1-Rhodamine B_25_0.05 NP2_26_0.1
Q07011 1.566238                1.580319
Q15109 2.125594                2.136470
Q9UNG2 1.642435                1.642868
P31749 1.676334                1.684229
Q15389 1.823491                1.655942
P05089 2.111452                2.146192

In [5]:
# creating a sample info df
sample_info_df = protein_df[,2:4] %>%
    unique() %>%
    # ensuring the sample ids are in the same order as the previous df
    arrange(match(Sample_ID, colnames(wide_protein_matrix)))

head(sample_info_df)

  Treatment       Sample_ID              Dose
1 Control         Control_2_NA           0.00
2 NP1             NP1_3_0.1              0.10
3 NP1-Rhodamine B NP1-Rhodamine B_5_0.1  0.10
4 NP1             NP1_6_0.05             0.05
5 NP1-Rhodamine B NP1-Rhodamine B_8_0.05 0.05
6 Control         Control_10_NA          0.00

Here we want to see how dose affects treatment's effect on protein expression, hence the interaction. ie. Treatment + Dose

If we wanted to control for dose, it would help us determine treatment's effect *regardless* of dose. ie. Treatment * Dose

Can't run an interaction for a dependent variable with only one dose, so to keep it consistent across all treatments I'll just stratify to see how dose modifies protein expression too.

In [20]:
# running limma
# comparing each tx group to the control while controlling for dose
design = model.matrix(~ Treatment, data = sample_info_df)
# MAY NOT WANT TO CONTROL FOR DOSE AND INSTEAD STRATIFY
linear_fit = lmFit(wide_protein_matrix, design)
limma_fit = eBayes(linear_fit)

treatments = colnames(design)[2:5]
limma_df = data.frame()
for (i in 1:length(treatments)){

    limma_results = topTable(limma_fit, coef = treatments[i], number = Inf) %>%
        rownames_to_column("UniProt_ID") %>%
        mutate(Treatment = treatments[i]) %>%
        # BH adjusted p value
        filter(adj.P.Val < 0.05)

    limma_df = rbind(limma_df, limma_results)

    }

# cleaning up the df
limma_df = limma_df[,c(1,2,5,6,8)] %>%
    mutate(Treatment = ifelse(grepl("Treatment", Treatment), 
                    unlist(strsplit(Treatment, split = "Treatment"))[2], Treatment))
colnames(limma_df)[3:4] = c("P Value", "P Adj")

# adding in meta data
limma_df = inner_join(limma_df, unique(protein_df[,6:8]))[,c(6,1,7,5,2:4)]
head(limma_df)

Joining with `by = join_by(UniProt_ID)`

  ELISA_ID UniProt_ID Protein_Name   Treatment logFC       P Value
1 nEL03731 P10909     CLU            NP1       -0.39103849 9.888882e-11
2 nEL04021 O00300     TNFRSF11B      NP1       -0.38900977 1.191029e-07
3 nEL00061 P10147     CCL3           NP1        0.11212664 1.258325e-07
4 nEL08971 Q99538     LGMN           NP1       -0.07179324 2.016804e-07
5 nEL03101 Q15389     Angiopoietin-1 NP1       -0.08516778 4.472279e-07
6 nEL01261 P49767     VEGF-C         NP1       -0.06259984 9.118955e-07
  P Adj
1 2.768887e-08
2 1.174437e-05
3 1.174437e-05
4 1.411763e-05
5 2.504476e-05
6 4.255512e-05

In [22]:
limma_df %>%
    filter(`P Adj` < 0.05)

    ELISA_ID UniProt_ID Protein_Name   Treatment logFC       P Value
1   nEL03731 P10909     CLU            NP1       -0.39103849 9.888882e-11
2   nEL04021 O00300     TNFRSF11B      NP1       -0.38900977 1.191029e-07
3   nEL00061 P10147     CCL3           NP1        0.11212664 1.258325e-07
4   nEL08971 Q99538     LGMN           NP1       -0.07179324 2.016804e-07
5   nEL03101 Q15389     Angiopoietin-1 NP1       -0.08516778 4.472279e-07
6   nEL01261 P49767     VEGF-C         NP1       -0.06259984 9.118955e-07
7   nEL01981 Q99988     GDF-15 (MIC-1) NP1        0.06496027 1.185311e-06
8   nEL02901 P27930     IL-1 R2        NP1        0.06361153 6.223855e-06
9   nEL04541 P01135     TGFA           NP1        0.06811369 3.477226e-05
10  nEL00441 Q9H2A7     CXCL16         NP1       -0.09078067 8.007048e-05
11  nEL00212 O00626     CCL22          NP1       -0.05282277 8.150077e-05
12  nEL03981 P10646     TFPI           NP1        0.08798026 1.456093e-04
13  nEL00191 P78556     CCL20          NP1       -0.10040706 2.229177e-04
14  nEL01611 Q13007     IL-24          NP1       -0.04646637 2.299774e-04
15  nEL01581 P00749     uPA            NP1       -0.04371913 4.578651e-04
16  nEL09441 P20701     ITGAL          NP1       -0.04927391 5.033423e-04
17  nEL06601 P20023     CR2            NP1        0.02837691 1.841242e-03
18  nEL02601 O75509     DR6            NP1        0.03249313 1.863271e-03
19  nEL01164 P01374     TNF beta       NP1        0.06300873 2.223688e-03
20  nEL05971 P07711     CTSL           NP1       -0.03164939 2.464596e-03
21  nEL00702 P05231     IL-6           NP1        0.03889642 2.524637e-03
22  nEL12921 P43629     KIR3DL1        NP1        0.05459746 2.820219e-03
23  nEL03731 P10909     CLU            NP1       -0.29364234 1.339356e-08
24  nEL01981 Q99988     GDF-15 (MIC-1) NP1        0.08055454 4.569103e-08
25  nEL08971 Q99538     LGMN           NP1       -0.07260130 1.699842e-07
26  nEL02901 P27930     IL-1 R2        NP1        0.05685861 2.615554e-05
27  nEL00061 P10147     CCL3           NP1        0.07579332 2.912442e-05
28  nEL00212 O00626     CCL22          NP1       -0.04884819 1.925918e-04
29  nEL04021 O00300     TNFRSF11B      NP1       -0.22112604 2.012624e-04
30  nEL04541 P01135     TGFA           NP1        0.05796624 2.149341e-04
⋮   ⋮        ⋮          ⋮              ⋮         ⋮           ⋮
74  nEL00253 Q9Y258     CCL26          NP1        0.05293643 1.878837e-03
75  nEL11471 Q14653     IRF3           NP1       -0.03017844 2.211941e-03
76  nEL01061 P09238     MMP-10         NP1       -0.03891111 2.415082e-03
77  nEL08911 Q99665     IL12RB2        NP1        0.05292258 2.657783e-03
78  nEL00532 P10144     Granzyme B     NP1        0.05889080 3.509614e-03
79  nEL04131 P00734     F2             NP1       -0.03650100 3.731968e-03
80  nEL12171 Q5VWK5     IL23R          NP1        0.05939462 4.722763e-03
81  nEL00561 P05362     ICAM-1         NP1       -0.05090254 4.861664e-03
82  nEL04271 P31749     AKT1           NP1        0.02678900 6.223880e-03
83  nEL01321 Q5ZPR3     CD276 (B7-H3)  NP1       -0.04032198 6.368920e-03
84  nEL00102 P80075     CCL8           NP1        0.06842939 6.404452e-03
85  nEL00391 P02778     CXCL10         NP1       -0.05490798 6.483238e-03
86  nEL03731 P10909     CLU            NP1       -0.50752474 5.237261e-09
87  nEL01152 P01375     TNF alpha      NP1       -0.13925744 6.696651e-09
88  nEL03101 Q15389     Angiopoietin-1 NP1       -0.16516278 3.134793e-08
89  nEL00441 Q9H2A7     CXCL16         NP1       -0.22749201 2.665589e-07
90  nEL00061 P10147     CCL3           NP1        0.15690299 1.252785e-06
91  nEL00351 P42830     CXCL5          NP1       -0.18309498 7.505119e-06
92  nEL09101 P19875     CXCL2          NP1       -0.11067501 9.989861e-06
93  nEL03981 P10646     TFPI           NP1       -0.16507083 2.936061e-05
94  nEL01261 P49767     VEGF-C         NP1       -0.07058007 1.065483e-04
95  nEL04021 O00300     TNFRSF11B      NP1       -0.38159081 1.106189e-04
96  nEL01611 Q13007     IL-24          NP1       -0.07938990 1.419279e-04
97  nEL00212 O00626     CCL22          NP1       -0.08186438 1.457698e-04
98  nEL08971 Q99538     LGMN           NP1       -0.06016277 7.796652e-04
99  nEL01641 P20809     IL-11          NP1       -0.04846032 9.554523e-04
100 nEL00311 P09341     CXCL1          NP1       -0.05488650 1.279677e-03
101 nEL07501 P09601     HMOX1          NP1       -0.05602766 1.624811e-03
102 nEL00921 Q8IZJ0     IL-28A         NP1       -0.05676183 1.657449e-03
103 nEL02991 Q03405     uPA R          NP1       -0.04027536 2.712266e-03
    P Adj
1   2.768887e-08
2   1.174437e-05
3   1.174437e-05
4   1.411763e-05
5   2.504476e-05
6   4.255512e-05
7   4.741242e-05
8   2.178349e-04
9   1.081804e-03
10  2.074565e-03
11  2.074565e-03
12  3.397550e-03
13  4.599548e-03
14  4.599548e-03
15  8.546815e-03
16  8.808490e-03
17  2.898422e-02
18  2.898422e-02
19  3.277015e-02
20  3.366182e-02
21  3.366182e-02
22  3.589370e-02
23  3.750195e-06
24  6.396744e-06
25  1.586519e-05
26  1.630968e-03
27  1.630968e-03
28  7.289651e-03
29  7.289651e-03
30  7.289651e-03
⋮   ⋮
74  1.348909e-02
75  1.548359e-02
76  1.649324e-02
77  1.771856e-02
78  2.285330e-02
79  2.374889e-02
80  2.938608e-02
81  2.959274e-02
82  3.630613e-02
83  3.630613e-02
84  3.630613e-02
85  3.630613e-02
86  9.375311e-07
87  9.375311e-07
88  2.925807e-06
89  1.865913e-05
90  7.015595e-05
91  3.502389e-04
92  3.995945e-04
93  1.027621e-03
94  3.097328e-03
95  3.097328e-03
96  3.401296e-03
97  3.401296e-03
98  1.679279e-02
99  1.910905e-02
100 2.388731e-02
101 2.729916e-02
102 2.729916e-02
103 4.219081e-02